<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   openpay
 * @package    OP_Openpayccard00
 * @copyright  Copyright (c) 2013 Openpay (http://www.twv.com.tw) */
 */
?>
<?php 
	echo $this->getMethod()->getTitle() . '<br/>';
	if ($this->getInfo()->getLastTransId() == '') {
		echo '<em>' . Mage::helper('openpaychinapay')->__($this->getMethodCode().':You will be redirected to Ecbank website when you place an order.') . '</em>';
	} else {
	    echo Mage::helper('openpaychinapay')->__('Credit Card Type: %s', $this->htmlEscape($this->getInfo()->getCcType())) . '<br/>';
		echo Mage::helper('openpaychinapay')->__('您的交易單號: %s', $this->htmlEscape($this->getInfo()->getLastTransId())) . '<br/>';
	}
?>